package info.inpureprojects.INpureCore.Scripting

import info.inpureprojects.INpureCore.API.TocManager
import info.inpureprojects.INpureCore.INpureCore
import info.inpureprojects.INpureCore.modInfo
import net.minecraftforge.fml.common.DummyModContainer
import net.minecraftforge.fml.common.FMLCommonHandler
import net.minecraftforge.fml.common.ModMetadata

import java.lang.reflect.Field

/**
 * Created by den on 1/7/2015.
 */
class ModContainerScript extends DummyModContainer{

    private File source;

    public ScriptModContainer(TocManager.TableofContents toc, File source) {
        ModMetadata META = new ModMetadata()
        META.authorList = "${toc.getAuthor()}";
        META.autogenerated = true
        META.credits = ""
        META.description = "Fake mod container generated by the INpureCore script engine."
        META.modId = toc.getTitle()
        META.name = toc.getTitle()
        META.parent = modInfo.modid
        META.parentMod = FMLCommonHandler.instance().findContainerFor(INpureCore.instance)
        META.version = toc.getVersion()
        Field f = this.getClass().getSuperclass().getDeclaredField("md")
        f.setAccessible(true)
        f.set(this, META)
        this.source = source
    }

    @Override
    Class<?> getCustomResourcePackClass() {
        return ResourcePackScript.class;
    }

    @Override
    File getSource() {
        return this.source;
    }

}
