package info.inpureprojects.INpureCore.Scripting

import info.inpureprojects.INpureCore.API.TocManager
import info.inpureprojects.INpureCore.INpureCore
import info.inpureprojects.INpureCore.modInfo
import net.minecraftforge.fml.common.DummyModContainer
import net.minecraftforge.fml.common.FMLCommonHandler
import net.minecraftforge.fml.common.ModMetadata

import java.lang.reflect.Field

/**
 * Created by den on 1/9/2015.
 */
class ModContainerInternal extends DummyModContainer{

    private File source;

    ModContainerInternal(TocManager.TableofContents toc) {
        ModMetadata META = new ModMetadata()
        META.authorList = [toc.getAuthor()]
        META.autogenerated = true
        META.credits = ""
        META.description = "Asset loader generated by INpureCore."
        META.modId = toc.getTitle()
        META.name = toc.getTitle()
        META.parent = modInfo.modid
        META.parentMod = FMLCommonHandler.instance().findContainerFor(INpureCore.instance)
        META.version = toc.getVersion()
        Field f = this.getClass().getSuperclass().getDeclaredField("md")
        f.setAccessible(true)
        f.set(this, META)
        this.source = new File("thisisafakedirectory");
    }

    @Override
    File getSource() {
        return this.source;
    }
}
